### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sullyj3**
Current year :)

### CODE REVIEW

**Comment by phase** [comment]
You should have waited 4 months for 2017 ;)

**Comment by withoutboats** [comment]
Could you amend this to "the 21st century" so we don't have to do this again next year? :-)

**Comment by sullyj3** [comment]
Done! I can squash when I get home if you like.

**Comment by withoutboats** [comment]
Please do. I'd squash it, but I'm worried GitHub will change the attribution if I do.

**Comment by phase** [comment]
You can pull the changes and squash through a rebase. That will keep the author of the commit.

**Comment by ararslan** [comment]
GitHub has squash on merge. That should preserve all authorship information.

**Pull request closed without merging**
