### PR TITLE
Subdividable screens.

### PR DESCRIPTION
**Pull request by withoutboats**
Introduce a layer of indirection between `Terminal` and `CharGrid`,
using the `Screen` type, which allows a `Terminal` to contain multiple
`CharGrids` in different sections of the visible screen.

Prior to this commit, a single `Terminal` contained a stack of
`CharGrid`s, which each filled the entire size of the `Terminal` window.

Now, a single `Terminal` contains a single `Screen`, which is divided
into `ScreenSection`s. Each `ScreenSection` is a rectangular section of
the screen. They are formed by splitting an existing section into two
along a horizontal or vertical axis. This means that the relationship
between sections that exist is always a binary tree. Each
`ScreenSection` has an unsigned 64-bit tag. One section is identified as
the 'active section' - commands that apply to the `CharGrid` are applied
to the grid contained in this section.

Each section contains a non-empty stack of `Panel`s. A `Panel` can take
one of two forms: either it contains a `CharGrid`, or it is split into
two parts, each of which contains a `ScreenSection`. As a result, there
is a mutually recursive relationship between the definition of
`ScreenSection` and `Panel`, which allows for considerable flexibility
in adjusting the layout screen, while still maintaining a certain level
of restraint.

This commit and its associated commit to notty-encoding add or modify
several commands to the notty protocol:
- **PUSH BUFFER** is now **PUSH PANEL**, and takes as an argument the
  tag of the screen section being pushed to. If no argument is passed, a
  panel is pushed to the active section. The panel that is pushed always
  contains a single character grid. It also takes a boolean argument,
  which determines whether or not the grid retains offscreen data as it
  scrolls.
- **POP BUFFER** is now **POP PANEL**, and also takes as an argument the
  tag of screen section to pop from. If no argument is passed, the top
  panel of the active section is popped. A stack with 1 member cannot be
  popped from.
- **SPLIT PANEL** describes splitting a panel into two. It takes
  arguments defining the axis and position of the split, which panel the
  contents should be saved to, how resizing of child sections should be
  handled, and whether or not the grid in the new panel should retain
  offscreen data as it scrolls. Panels which are already split _can_ be
  split again; the existing split sections are resized into the
  identified saved sections.
- **UNSPLIT PANEL** describes removing the split from a panel. It takes
  an argument identifying which of the two sections in this panel should
  be saved. The stack of the saved section will be pushed to the top of
  the section this panel is on top of; the stack of the unsaved section
  will be destroyed.
- **ADJUST PANEL SPLIT** allows an existing split panel's split to be
  moved or adjusted. It takes arguments defining the axis and position of
  the split, and how resizing of the child sections should be handled. It
  performs no action it the section's top is a unsplit panel.
- **ROTATE SECTION DOWN** rotates down the stack, putting the top of
  the stack on the bottom.
- **ROTATE SECTION UP** rotates up the stack, putting the bottom of the
  stack on the top.
- **SWITCH ACTIVE SECTION** switches which section is active. It will
  only perform a switch if the top panel of the target section is a single
  character grid.

### CODE REVIEW

**Comment by withoutboats** [comment]
@waynr in response to #15, this branch should now scroll correctly to keep the cursor on the screen.

**Comment by waynr** [comment]
Cool, so do you think this is ready to review seriously or is there more work to be done?

**Comment by withoutboats** [comment]
At minimum I need to get "stacking grids" implemented before this is ready for review.

**Comment by withoutboats** [comment]
@waynr I still have a few more tests and comments to write on this, but feedback would be appreciated. This branch has gone through a lot of iteration, and I'm happy with the outcome now.

**Comment by waynr** [comment]
@withoutboats I've taken a short look so far, I'll definitely spend more time on it this weekend. FYI, I am organizing a "Rust Hack Session" meetup in the Portland, OR area tomorrow and will be seeing if I can get other folks interested in `notty` so if you have any ideas for low-hanging fruit for newcomers it'd be a good idea to create separate github issues for them to tackle.

**Comment by withoutboats** [comment]
@waynr I've posted a few help wanted issues, I'll try to come up with more.

I've also extended this PR a bit, it now implements 8 commands which I think are a very strong base for this feature. These are the ways I think this feature could be extended in the future:
- A few new commands like 'Clear Panel' or 'Swap Panels' probably make sense.
- The arguments to these commands could definitely be refined. ResizeRule in particular is just a first guess. Actual attempts at use will tell us what kinds of arguments make sense.
- A kind of panel could be added which behaves like a pop-up or a modal window, implementing a grid over only a region of the section that contains it.

**Comment by waynr** [comment]
@withoutboats could you explain the advantage of the multigrid feature existing at the terminal protocol level? Why would an application developer use this rather than implementing the "pane" concept within their application? It might help me to understand the goal if you write an example terminal app demonstrating the use of this part of the protocol.

When I think of this multi-grid behavior and the ways it might be used, I think of `tmux`, `screen`, or `vim`, each of which has their own specific way of subdividing a terminal screen.

**Comment by withoutboats** [comment]
Subdividing the screens into multiple grids is better implemented in the terminal rather than in the controlling process. The current set up has several flaws, which this protocol solves:
- It requires the controlling process to reimplement a lot of display logic which is already implemented on the screen. The two programs are redundant because of this.
- Except in the naive case of an undivided grid, the terminal is unable to save off-screen state, requiring the controlling process to retransmit data over the tty whenever the user moves the cursor, even if this data has already been transmitted. This is redundant in general, and over ssh can contribute to latency spikes.
- It is more difficult for people to write their own applications when they have to re-implement this logic.
- Multiple implementations of the same logic in different applications means more possibilities of bugs.
- The terminal does not know it contains multiple grids, and can't integrate them with the host GUI - e.g. they cannot scroll independently of one another.

ANSI terminals do have some commands for subdividing the screen, and these commands are used (by vim for example), but they are finnicky, limited, and difficult to deal with. They involve 'setting the page margins,' and then certain move commands will stop at the 'margin,' whereas others will move beyond it. You can see more info [here](http://www.vt100.net/docs/vt510-rm/DECSLRM) and [here](http://www.vt100.net/docs/vt510-rm/DECSTBM).

While programs that would make use of this feature, like the ones you listed, present a different user interface for manipulating the subdivisions of the screen, all of them would be able to use this API to implement their behavior.

**Comment by waynr** [comment]
@withoutboats cool, thanks for the explanation.

**Comment by withoutboats** [comment]
> Except in the naive case of an undivided grid, the terminal is unable to save off-screen state, requiring the controlling process to retransmit data over the tty whenever the user moves the cursor, even if this data has already been transmitted. This is redundant in general, and over ssh can contribute to latency spikes.

I want to add that this becomes an even bigger problem when combined with the fact that the grid can now contain images. Having to send images over ssh over and over again as the user scrolls up and down the page would be very unfortunate.

**Comment by waynr** [comment]
```
   Compiling notty v0.1.0 (file:///home/wayne/projects/notty)
src/command/panel.rs:53:59: 53:68 error: attempted access of field `rule` on type `&notty_encoding::cmds::panel::AdjustPanelSplit`, but no field with that name was found
src/command/panel.rs:53         terminal.adjust_split(self.adjust_tag, self.kind, self.rule);
                                                                                  ^~~~~~~~~
src/output/notty/mod.rs:153:31: 153:96 error: this function takes 2 parameters but 3 parameters were supplied [E0061]
src/output/notty/mod.rs:153                     wrap(Some(AdjustPanelSplit::new(kind, rule, u64::decode(args.next(), None))))
                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/output/notty/mod.rs:153:31: 153:96 help: run `rustc --explain E0061` to see a detailed explanation
error: aborting due to 2 previous errors
Could not compile `notty`.

To learn more, run the command again with --verbose.
```

**Comment by withoutboats** [comment]
Forgot to push, should be fixed now.

**Comment by waynr** [comment]
It compiles and runs, but when I attempt to run `rub imagetest.rb` where the image would cause the terminal to scroll I get this stacktrace:

```
     Running `target/debug/scaffolding-terminal`
thread '<main>' panicked at 'assertion failed: bottom > top', /home/wayne/projects/notty/notty-encoding/src/args/region.rs:26
stack backtrace:
   1:     0x55a93adf3550 - sys::backtrace::tracing::imp::write::h752705b18648d1caEIv
   2:     0x55a93adf683f - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.45061
   3:     0x55a93adf64b8 - panicking::default_handler::hd7da873c55525eaaRxA
   4:     0x55a93adecc3c - sys_common::unwind::begin_unwind_inner::h9832d329b70049c9Xwu
   5:     0x55a93ade8b27 - sys_common::unwind::begin_unwind::h4288770499111532530
                        at ../src/libstd/sys/common/unwind/mod.rs:219
   6:     0x55a93ade897a - args::region::Region::new::h0311cf40afc36201vrb
                        at /home/wayne/projects/notty/scaffolding/<std macros>:3
   7:     0x55a93ad806a5 - datatypes::iter::CoordsIter::from_area::h4c4d531abce8fba5wib
                        at /home/wayne/projects/notty/src/datatypes/iter.rs:68
   8:     0x55a93ad79975 - terminal::char_grid::CharGrid::write::hf7906ae00cc849f0icg
                        at /home/wayne/projects/notty/src/terminal/char_grid/mod.rs:106
   9:     0x55a93ad78b68 - command::put::Put.Command::apply::h4efc382685a7888fbYa
                        at /home/wayne/projects/notty/src/command/put.rs:48
  10:     0x55a93ad6f303 - terminal::Terminal::apply::h595f6a961619a52c0lj
                        at /home/wayne/projects/notty/src/terminal/mod.rs:49
  11:     0x55a93ad40bb2 - commands::CommandApplicator::apply::h14480a142c58c884Cba
                        at src/commands.rs:40
  12:     0x55a93ad408af - main::_$u7b$$u7b$closure$u7d$$u7d$::closure.11677
                        at src/main.rs:102
  13:     0x55a93ad6d2b4 - source::trampoline::__rust_abi
                        at /home/wayne/.multirust/cargo/registry/src/github.com-88ac128001ac3a9a/glib-0.0.7/src/source.rs:35
  14:     0x55a93ad6d224 - source::trampoline::h6139efeb8309a3dd07a
  15:     0x7f7a249d18f2 - <unknown>
  16:     0x7f7a249d0e89 - g_main_context_dispatch
  17:     0x7f7a249d122f - <unknown>
  18:     0x7f7a249d1551 - g_main_loop_run
  19:     0x7f7a260d7ed4 - gtk_main
  20:     0x55a93ad4a1e5 - rt::main::hf825ee190a9559da6ha
                        at /home/wayne/.multirust/cargo/registry/src/github.com-88ac128001ac3a9a/gtk-0.0.6/src/rt.rs:99
  21:     0x55a93ad21178 - main::hba872322dc9ed708Dga
                        at src/main.rs:155
  22:     0x55a93adf6114 - sys_common::unwind::try::try_fn::h12046357363932425278
  23:     0x55a93adf27db - __rust_try
  24:     0x55a93adf5bab - rt::lang_start::h3e6bf90cd10c800fXpA
  25:     0x55a93ad43939 - main
  26:     0x7f7a2460360f - __libc_start_main
  27:     0x55a93ad20598 - _start
  28:                0x0 - <unknown>
Process didn't exit successfully: `target/debug/scaffolding-terminal` (exit code: 101)
```

**Comment by withoutboats** [comment]
This error is resulting from [this change](https://github.com/withoutboats/notty-encoding/pull/4/files#diff-8b7d8ff8d74e40e4a9cd8f3c00c2a8f5R25), which has incidentally revealed a bug that arises when drawing images in the bottom line of the screen. There's an off-by-one error involved, I'm working through exactly where it is.

**Comment by withoutboats** [comment]
I fixed the off-by-one error directly on master and rebased this. I've also added documentation of the model used by multigrid commands in the new `docs` folder on this branch.

**Comment by waynr** [comment]
Hey sorry for not getting to this, I've been working 11 hour days the past week and trying not to get right back on the computer afterward. I did try it out again and `notty` no longer crashes but does give a strange visual artifact instead of properly displaying the image from `imagetest.rb`:

image of visual artifact

**Comment by waynr** [comment]
@withoutboats I'd actually be fine with merging this PR as-is and submitting a bug report for the visual artifact problem.

**Comment by withoutboats** [comment]
I think right now images that go across the boundary of the screen are just full of bugs. I haven't tested this but I'm pretty sure if the image starts above the top of the screen it just won't display the image at all. 

The issue here seems to be a scrolling issue - the cursor moved to the next line instead of to beneath the image.

I think I'll merge this and the other PR in either in the next few minutes or tomorrow some time. I don't think this implementation is final by any means, but I think its a solid basis for building out the feature.

**Comment by waynr** [comment]
So master branch is currently borked due to the merge on `notty-encoding` but no merge on this branch.

**Comment by withoutboats** [comment]
Crap, told myself I would squash this later and then just put it off.

**Comment by withoutboats** [comment]
Squashed, rebased and pushed.

**Pull request closed without merging**
