### PR TITLE
Fix text line spacing using font ascent and descent attributes.

### PR DESCRIPTION
**Pull request by waynr**

### CODE REVIEW

**Comment by waynr** [comment]
This problem was mentioned in #10 and of course difficult to miss just running the scaffolding terminal for the first time. Sadly, I don't know how to write a test for something like this.

**Comment by withoutboats** [comment]
My god is this how it works? I could not figure it out from the documentation of cairo. Thanks, will do a manual test, confirm, and merge.

The best way to test this automatically would be to have a set of fonts with known pixel dimensions, compare the output of this function to those dimensions. Someday, maybe, notty will be well-tested.

**Comment by withoutboats** [comment]
Pretty sure the line spacing is still off - now its too large. But that's an unambiguous improvement over being too small.

**Comment by waynr** [comment]
This was mostly a wild guess based on https://en.wikipedia.org/wiki/Baseline_%28typography%29#/media/File:Typography_Line_Terms.svg and http://cairographics.org/manual/cairo-cairo-scaled-font-t.html#cairo-font-extents-t

**Comment by waynr** [comment]
@withoutboats I was just thinking about this and I recall reading the following from the `cairo_font_extents_t` documentation:

> If you call cairo_scale(cr, 2.0, 2.0), text will be drawn twice as big, but the reported text extents will not be doubled. They will change slightly due to hinting (so you can't assume that metrics are independent of the transformation matrix), but otherwise will remain unchanged.

If text is being scaled anywhere in `notty`, `notty_cairo`, or `scaffolding` using that function the sizes in this struct won't change. I wonder if `cairo_scale` is used to change rendered font size...?

**Comment by withoutboats** [comment]
> I wonder if `cairo_scale` is used to change rendered font size...?

Not explicitly. (The only place it would be happening, btw, is `notty_cairo`.) It could be that the font is being scaled inside the gtk-rs libraries, but I don't think so.

Of course, this is a weakness of `notty` right now - font size is not configurable.

> This was mostly a wild guess based on https://en.wikipedia.org/wiki/Baseline_%28typography%29#/media/File:Typography_Line_Terms.svg and http://cairographics.org/manual/cairo-cairo-scaled-font-t.html#cairo-font-extents-t

This is what's so frustrating! This text specifically says that height is the value we want for this purpose, but it is clearly not the right value:

> `height`: the recommended vertical distance between baselines when setting consecutive lines of text with the font. This is greater than ascent + descent by a quantity known as the line spacing or external leading. When space is at a premium, most fonts can be set with only a distance of ascent + descent between lines.

**Pull request merged**
