### PR TITLE
Fix tab right case.

### PR DESCRIPTION
**Pull request by waynr**
Naive fix for #13

### CODE REVIEW

**Comment by withoutboats** [comment]
I've got to try to figure out what the hell this boolean is about, I'm sure I excluded this case for a reason.

Sorry I am a very sloppy side project maintainer.

**Comment by waynr** [comment]
@withoutboats https://github.com/withoutboats/notty/commit/c6604df143159c6251ad50b183a2b69d83d69846

With this in mind I think the logic on this case https://github.com/withoutboats/notty/blob/master/src/datatypes/mod.rs#L149 should be sufficient to prevent anything bad happening if `true` is set and the new position would not exceed the width of the window.

**Comment by withoutboats** [comment]
You're right, if the cursor isn't at the edge of a grid it doesn't matter if it should wrap or not. Could you also make this change to the similar tab-left branch, then I'll merge?

Does this close #13 on your system, or does your `ls` tab past the end of the line as well?

**Comment by waynr** [comment]
This does close #13 in the sense that `ls` works, but it doesn't fix the case where the user tabs past the end of the line.

**Comment by waynr** [comment]
Also, I made the requested left-tab movement change.

**Comment by withoutboats** [comment]
Merged in. :smile: It fixed `ls` on my system too, so I closed that particular issue (breaking the most obvious command to run to check if its working is a bigger problem than not allowing tab right past the end of line).

**Pull request merged**
